---
version: "2"

x-environment: &commonEnvironment
    PORT: 7343
    tor_interval: 10

services:
  tor-socks-proxy:
    container_name: tor-socks-proxy
    #image: peterdavehello/tor-socks-proxy:latest
    logging: 
      driver: none
    environment: *commonEnvironment
    build: 
      context: .
      args:
        - PORT=7343   
        - tor_interval=10
    restart: unless-stopped
    networks:
      - net
  ubuntu:
    container_name: tor-consumer
    image: liransehayk/tor_consumer
    entrypoint: ["/work/entryscript.sh"] 
    environment: *commonEnvironment
    depends_on:
      - tor-socks-proxy
    networks:
      - net
networks:
  net:
