---
version: "3.4"

x-common-variables: &commonEnvironment
    PORT: ${PORT}
    tor_interval: ${tor_interval}

services:
  tor-socks-proxy:
    container_name: tor-socks-proxy
    #image: peterdavehello/tor-socks-proxy:latest
    logging: 
      driver: none
    environment: *commonEnvironment
    build: 
      context: .
      args:
        - PORT=${PORT}   
        - tor_interval=${tor_interval}
    restart: unless-stopped
    networks:
      - net
  ubuntu:
    container_name: tor-consumer
    build:
      context: .
      dockerfile: Dockerfile-tor_consumer
    entrypoint: ["/work/entryscript.sh"] 
    environment: *commonEnvironment
    depends_on:
      - tor-socks-proxy
    networks:
      - net
networks:
  net:
